### ISSUE TITLE
Ajouter un Système de documentation pour les api REST

### ISSUE THREAD

**Issue by MercierCorentin** [AezardSR/Le_Flamant_Bleu_API#11]
https://blog.quickadminpanel.com/laravel-api-documentation-with-openapiswagger/

C'est le niveau 3 (dernier niveau) du modèle de maturité des API REST: https://guide-api-rest.marmicode.fr/api-rest/le-modele-de-maturite-de-richardson

**Comment by RomainZieba** [comment]
J'ai avancé sur la documentation de swagger.
en particulier sur [authController](https://github.com/AezardSR/Le_Flamant_Bleu_API/blob/feature-add-swagger/app/Http/Controllers/AuthController.php)

voici un exemple avec le token reçu grâce à la connexion :
https://github.com/AezardSR/Le_Flamant_Bleu_API/blob/ac134587b59b7e167fca6ae92fa078ff9befad42/app/Http/Controllers/AuthController.php#L215-L238

cette ligne permet d'ajouter le token
https://github.com/AezardSR/Le_Flamant_Bleu_API/blob/ac134587b59b7e167fca6ae92fa078ff9befad42/app/Http/Controllers/AuthController.php#L222

**Comment by BenjaminPmt** [comment]
Changement de certaines routes de l'api
modifications des migrations pour la suppression des clés étrangères en cascade
ajout de la doc swagger pour le MVP

**Comment by BenjaminPmt** [comment]
#36
