### ISSUE TITLE
Delete avec foreign key

### ISSUE THREAD

**Issue by Manon-POTEL** [AezardSR/Le_Flamant_Bleu_API#29]

**Comment by MercierCorentin** [comment]
https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html
```
Referential Actions

When an [UPDATE](https://dev.mysql.com/doc/refman/8.0/en/update.html) or [DELETE](https://dev.mysql.com/doc/refman/8.0/en/delete.html) operation affects a key value in the parent table that has matching rows in the child table, the result depends on the referential action specified by ON UPDATE and ON DELETE subclauses of the FOREIGN KEY clause. Referential actions include:

    CASCADE: Delete or update the row from the parent table and automatically delete or update the matching rows in the child table. Both ON DELETE CASCADE and ON UPDATE CASCADE are supported. Between two tables, do not define several ON UPDATE CASCADE clauses that act on the same column in the parent table or in the child table.

    If a FOREIGN KEY clause is defined on both tables in a foreign key relationship, making both tables a parent and child, an ON UPDATE CASCADE or ON DELETE CASCADE subclause defined for one FOREIGN KEY clause must be defined for the other in order for cascading operations to succeed. If an ON UPDATE CASCADE or ON DELETE CASCADE subclause is only defined for one FOREIGN KEY clause, cascading operations fail with an error.
    Note

    Cascaded foreign key actions do not activate triggers.

    SET NULL: Delete or update the row from the parent table and set the foreign key column or columns in the child table to NULL. Both ON DELETE SET NULL and ON UPDATE SET NULL clauses are supported.

    If you specify a SET NULL action, make sure that you have not declared the columns in the child table as NOT NULL.

    RESTRICT: Rejects the delete or update operation for the parent table. Specifying RESTRICT (or NO ACTION) is the same as omitting the ON DELETE or ON UPDATE clause.

    NO ACTION: A keyword from standard SQL. In MySQL, equivalent to RESTRICT. The MySQL Server rejects the delete or update operation for the parent table if there is a related foreign key value in the referenced table. Some database systems have deferred checks, and NO ACTION is a deferred check. In MySQL, foreign key constraints are checked immediately, so NO ACTION is the same as RESTRICT.

    SET DEFAULT: This action is recognized by the MySQL parser, but both [InnoDB](https://dev.mysql.com/doc/refman/8.0/en/innodb-storage-engine.html) and [NDB](https://dev.mysql.com/doc/refman/8.0/en/mysql-cluster.html) reject table definitions containing ON DELETE SET DEFAULT or ON UPDATE SET DEFAULT clauses.
   ```

**Comment by Manon-POTEL** [comment]
> https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html
> 
> ```
> Referential Actions
> 
> When an [UPDATE](https://dev.mysql.com/doc/refman/8.0/en/update.html) or [DELETE](https://dev.mysql.com/doc/refman/8.0/en/delete.html) operation affects a key value in the parent table that has matching rows in the child table, the result depends on the referential action specified by ON UPDATE and ON DELETE subclauses of the FOREIGN KEY clause. Referential actions include:
> 
>     CASCADE: Delete or update the row from the parent table and automatically delete or update the matching rows in the child table. Both ON DELETE CASCADE and ON UPDATE CASCADE are supported. Between two tables, do not define several ON UPDATE CASCADE clauses that act on the same column in the parent table or in the child table.
> 
>     If a FOREIGN KEY clause is defined on both tables in a foreign key relationship, making both tables a parent and child, an ON UPDATE CASCADE or ON DELETE CASCADE subclause defined for one FOREIGN KEY clause must be defined for the other in order for cascading operations to succeed. If an ON UPDATE CASCADE or ON DELETE CASCADE subclause is only defined for one FOREIGN KEY clause, cascading operations fail with an error.
>     Note
> 
>     Cascaded foreign key actions do not activate triggers.
> 
>     SET NULL: Delete or update the row from the parent table and set the foreign key column or columns in the child table to NULL. Both ON DELETE SET NULL and ON UPDATE SET NULL clauses are supported.
> 
>     If you specify a SET NULL action, make sure that you have not declared the columns in the child table as NOT NULL.
> 
>     RESTRICT: Rejects the delete or update operation for the parent table. Specifying RESTRICT (or NO ACTION) is the same as omitting the ON DELETE or ON UPDATE clause.
> 
>     NO ACTION: A keyword from standard SQL. In MySQL, equivalent to RESTRICT. The MySQL Server rejects the delete or update operation for the parent table if there is a related foreign key value in the referenced table. Some database systems have deferred checks, and NO ACTION is a deferred check. In MySQL, foreign key constraints are checked immediately, so NO ACTION is the same as RESTRICT.
> 
>     SET DEFAULT: This action is recognized by the MySQL parser, but both [InnoDB](https://dev.mysql.com/doc/refman/8.0/en/innodb-storage-engine.html) and [NDB](https://dev.mysql.com/doc/refman/8.0/en/mysql-cluster.html) reject table definitions containing ON DELETE SET DEFAULT or ON UPDATE SET DEFAULT clauses.
> ```

Rajouter ceci : `->onDelete('cascade');` dans les functions dans les migrations dans la partie des clés étrangères
Exemple : 
`Schema::table('parts',function ($table){
     $table->foreign('categories_id')->references('id')->on('categories')->onDelete('cascade');
  });`
